name: "\U0001FA79 Requests & Suggestions"
description: Suggest an icon or request changes
labels: "\U0001FA79 Requests & Suggestions"
assignees: walkxcode
body:
  - type: markdown
    attributes:
      value: "Thank you for your interest in contributing to our icon repository! To ensure that everything runs smoothly, we've set out some guidelines for contributors.\n## ðŸŒŸ Icon Specifications\n\n- Each icon should include both a **PNG** and **SVG** version. If an **SVG** cannot be found, then only a **PNG** version is required.\n\n- Each icon should be in **PNG** format and have a height of exactly **512px**. Width does not matter. â—ï¸(No upscales! If the correct size cannot be found, a smaller height will be accepted.)\n\n- Icons should be named after their full name, using the [Kebab Case](https://wiki.c2.com/?KebabCase) naming convention. For example, \"Facebook Messenger\" should be named `facebook-messenger.png`.\n\n- Monochrome icons should default to a dark version. Light versions should be named `service-light.png`. If a light version is not available, use [https://pinetools.com/colorize-image](https://pinetools.com/colorize-image) to change its color.\n"
  - type: checkboxes
    attributes:
      label: Contribution Guidelines
      options:
        - label:  I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: icon-name
    attributes:
      label: Icon Name
      description: What is the name of the icon you are contributing?
      placeholder: Enter icon name here
    validations:
      required: true
  - type: textarea
    id: icons
    attributes:
      label: Icon(s)
      description: >-
        Upload your icons here. You can do this by Copy-Pasting or Drag &
        Dropping the images.
      placeholder: Copy-Paste or Drag & Drop images here!
    validations:
      required: false
