name: 🗜️ PNG Compression

on:
  push:
    paths:
      - '**/*.png'
  workflow_dispatch:
  
jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zopfli
          
      - name: Compress PNGs
        run: |
          echo "🖼️  Compressing PNGs..."
          git diff --name-only HEAD^..HEAD | grep "\.png$" | xargs -P 4 -I{} sh -c 'echo "Compressing {}"; zopflipng -y {} {}' || true
          
      - name: Load to GitHub
        run: |-
          git config --global user.email "noreply@walkx.fyi"
          git config --global user.name "Dashboard Icons Bot"
          git add -A
          git commit -m ":clamp: Compresses PNGs" || exit 0
          git push
