name: 🗜️ PNG & SVG Compression

on:
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant
          sudo npm install -g svgo
          
      - name: Compress PNGs
        run: |
          echo "🖼️  Compressing PNGs..."
          find png/ -iname "*.png" -print0 | xargs -0 -I{} sh -c 'echo "Compressing {}"; pngquant --force --ext .png --skip-if-larger --speed 1 "{}"' || true

      - name: Compress SVGs
        run: |
          echo "🎨  Compressing SVGs..."
          find svg/ -iname "*.svg" -print0 | xargs -0 -I{} sh -c 'echo "Compressing {}"; svgo --quiet --multipass "{}"' || true
          
      - name: Load to GitHub
        run: |-
          git diff
          git config --global user.email "noreply@walkx.fyi"
          git config --global user.name "Dashboard Icons Bot"
          git add -A
          git commit -m ":clamp: Compresses PNGs & SVGs" || exit 0
          git push
